### ISSUE TITLE
Encore text in UTF-8 with ECI (Extended Channel Interpretation)

### ISSUE THREAD

**Issue by Laurent774** [whomwah/rqrcode#102]
Hi,
how we can encode data in UTF-8 and specify the ECI to UTF-8 ?
Or there is a way to set raw data ?

Thanks !!

**Comment by whomwah** [comment]
Hi,

I'm not 100% sure what you mean but the underlying `rqrcode_core` lib has these options:
https://github.com/whomwah/rqrcode_core#options
