### ISSUE TITLE
Resulting image blank

### ISSUE THREAD

**Issue by dvodvo** [whomwah/rqrcode#109]
This is a question.

I have not found any reference to this effect, but in testing QR code generation with a high number of characters, I have noted that consistently, past a certain quantity of characters, the image generated is a stream of #FFFFFF hashes.

If I increase the size to the image, then a proper QR code is generated.

The question is thus:  when a blank image (formed by a stream of #FFFFFF characters) is generated, is this indicative that the library cannot produce a QRcode with complete data and associated error correction ?

**Comment by thanostollos** [comment]
Hi @dvodvo, can you please elaborate on the issue?
For example:
1. what is the certain quantity of characters you are referring to? Can you give an example with any extra options you use?
2. what is the size of the image prior and after the increase?

I'm also evaluating the library.

Thank you for your feedback and report.

**Comment by dvodvo** [comment]
Basic unit is a string of 27 UTF-8 characters.

When generating a QR code of 35 such units at 120x120, I get blanks.

However, as of 240x240 50 such units can be generated. (Testing did not go further as use-case does not require it).
Naturally at 360x360 there is no issue.

Going to those image & data sizes also revealed another limitation: the reading device's capabilities.  Between HW, SW and the QR code itself, this becomes a fuzzy issue to pin down.  Same HW, ∆ SW != constant results.  Some apparently professional grade scanners have also been 'weaker' than mid- low-level smart phone scanners.

As for the library, I have no negative experiences.

**Comment by whomwah** [comment]
Thanks for the comments 👍  I'm afraid I'm unable to help in your research but
> As for the library, I have no negative experiences.
it's good to hear the library is working for you so I'm going to close this issue.
