### ISSUE TITLE
Invalid QR Code Generated at Level 15 EC Level H

### ISSUE THREAD

**Issue by jonwade** [whomwah/rqrcode#13]
Level 15 with error correction set to 'h' produces an invalid QR code.  All other levels seem OK.  Happens with any input. Possible boundary condition?  I'm using Ruby 1.9.3p0 and rQRcode 0.4.2. Have tested with ruby 1.8.7-p352 and get the same issue.  Can anyone else replicate?

**Comment by bjornblomqvist** [comment]
Do still have the code that triggers this?
