### ISSUE TITLE
Options for use_svg do not work

### ISSUE THREAD

**Issue by bravebox** [whomwah/rqrcode#142]
Is you set viewbox to true it does not generate the viewbox on the svg element.

When you set the use_path to true it still renders <rect/> elements.

**Comment by whomwah** [comment]
Hi,

If you could give me some examples as I'm not seeing this:

```ruby
> qr = RQRCode::QRCode.new("hello")
> qr.as_svg(viewbox: true, use_path: true)
=> "<?xml version=\"1.0\" standalone=\"yes\"?><svg version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" xmlns:ev=\"http://www.w3.org/2001/xml-events\" viewBox=\"0 0 231 231\" shape-rendering=\"crispEdges\"><path d=\"M0 0h7v7h-7zM8 0h2v2h-1v-1h-1zM11 0h2v2h-1v1h1v5h-1v-4h-1zM14 0h7v7h-7zM1 1v5h5v-5zM15 1v5h5v-5zM2 2h3v3h-3zM16 2h3v3h-3zM8 3h2v3h-1v-2h-1zM8 6h1v1h-1zM10 6h1v2h1v1h1v-1h1v3h-1v-1h-2v-1h-1zM2 8h1v1h-1zM4 8h3v1h-2v2h-1v-1h-1v-1h1zM8 8h1v3h-1zM17 8h1v1h-1zM20 8h1v3h-1v1h-1v-1h-3v-1h3v-1h1zM1 9h1v2h-2v-1h1zM6 10h1v1h-1zM10 10h1v2h-1zM3 11h1v1h1v-1h1v1h-1v1h-2zM6 12h1v1h-1zM8 12h2v1h1v-1h1v2h-1v1h-2v-1h-1zM13 12h2v1h-1v2h-1zM16 12h1v1h-1zM15 13h1v2h1v1h-1v2h-1v-2h-1v-1h1zM18 13h3v2h-3zM0 14h7v7h-7zM1 15v5h5v-5zM8 15h1v1h1v2h1v-2h1v-1h1v2h-1v1h-1v3h-2v-1h1v-1h-2v-1h1v-1h-1zM2 16h3v3h-3zM19 16h2v1h-1v1h-1v1h-1v-2h1zM14 18h1v1h-1zM16 18h1v2h-1zM20 18h1v1h-1zM13 19h1v1h-1zM19 19h1v1h1v1h-2zM14 20h2v1h-2z\" fill=\"#000\" transform=\"translate(0,0) scale(11)\"/></svg>"
```

**Comment by bravebox** [comment]
Thanks @whomwah for your reply. We use a helper to generate the SVG.

`# app/helpers/qr_code_helper.rb
module QrCodeHelper
    def qr_code_image(data)
        qrcode = RQRCode::QRCode.new(data)
        svg = qrcode.as_svg(
            color: "000",
            shape_rendering: "crispEdges",
            module_size: 11,
            standalone: true,
            use_path: true,
            viewbox: true,
        )

        # Set your desired viewbox width and height
        viewbox_width = 231
        viewbox_height = 231

        # Modify the viewbox attribute in the SVG
        svg.sub!(/<svg (.*?)>/, "<svg viewBox=\"0 0 #{viewbox_width} #{viewbox_height}\" \\1>")
    end
end
 `

The generated SVG does not generate a viewBox or uses <path /> elements. 

If fixed it by setting my own viewbox the same size as the generated so I could at least scale the SVG.

Thanks

**Comment by whomwah** [comment]
Thanks, let me take a look later and get back to you. I think it may be a shortcoming in the `as_svg` extension.

**Comment by whomwah** [comment]
So just tried this locally with the latest version of `rqrcode`:

```bash
> qr = RQRCode::QRCode.new("hello")
> qr.as_svg(color: "000", shape_rendering: "crispEdges", module_size: 11, standalone: true, use_path: true, viewbox: true)
=> "<?xml version=\"1.0\" standalone=\"yes\"?><svg version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" xmlns:ev=\"http://www.w3.org/2001/xml-events\" viewBox=\"0 0 231 231\" shape-rendering=\"crispEdges\"><path d=\"M0 0h7v7h-7zM8 0h2v2h-1v-1h-1zM11 0h2v2h-1v1h1v5h-1v-4h-1zM14 0h7v7h-7zM1 1v5h5v-5zM15 1v5h5v-5zM2 2h3v3h-3zM16 2h3v3h-3zM8 3h2v3h-1v-2h-1zM8 6h1v1h-1zM10 6h1v2h1v1h1v-1h1v3h-1v-1h-2v-1h-1zM2 8h1v1h-1zM4 8h3v1h-2v2h-1v-1h-1v-1h1zM8 8h1v3h-1zM17 8h1v1h-1zM20 8h1v3h-1v1h-1v-1h-3v-1h3v-1h1zM1 9h1v2h-2v-1h1zM6 10h1v1h-1zM10 10h1v2h-1zM3 11h1v1h1v-1h1v1h-1v1h-2zM6 12h1v1h-1zM8 12h2v1h1v-1h1v2h-1v1h-2v-1h-1zM13 12h2v1h-1v2h-1zM16 12h1v1h-1zM15 13h1v2h1v1h-1v2h-1v-2h-1v-1h1zM18 13h3v2h-3zM0 14h7v7h-7zM1 15v5h5v-5zM8 15h1v1h1v2h1v-2h1v-1h1v2h-1v1h-1v3h-2v-1h1v-1h-2v-1h1v-1h-1zM2 16h3v3h-3zM19 16h2v1h-1v1h-1v1h-1v-2h1zM14 18h1v1h-1zM16 18h1v2h-1zM20 18h1v1h-1zM13 19h1v1h-1zM19 19h1v1h1v1h-2zM14 20h2v1h-2z\" fill=\"#000\" transform=\"translate(0,0) scale(11)\"/></svg>"
irb(main):008:0>
```

As you can see the output has the `viewBox` information

The latest version of `rqrcode` is `2.2.0` so I think you need to upgrade your version and all should be well.
