### ISSUE TITLE
RQRCode::QRCodeRunTimeError: code length overflow. (372>288) 

### ISSUE THREAD

**Issue by meetme2meat** [whomwah/rqrcode#15]
When Generating "QRCode"  the following above error was generated 

The the string whose Qrcode is resulting in error
 
"http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_div_align"

The Code

```ruby
 RQRCode::QRCode.new("http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_div_align", :size => 4, :level => :h )
```

```ruby

RQRCode::QRCodeRunTimeError: code length overflow. (540>288)

```

**Comment by mmcraedhcu** [comment]
I've had mostly great results with rqrcode-with-patches, with one exception.

You can view details here https://github.com/bjornblomqvist/rqrcode/compare/whomwah:master...master

From my experience (and I encourage you to test this for yourself), RQRCode::QRCode.new(qr_text) fails, throwing 'code length overflow' when 194 > qr_text.length > 221

It's a bizarre bug -- normally it auto-selects the proper size very well. Can anyone else confirm / comment on this?

**Comment by bjornblomqvist** [comment]
I have added a hint in the error on how to fix it. 
```ruby
RQRCode::QRCodeRunTimeError: code length overflow. (540>288) (Try a larger size!)
```

**Comment by penne12** [comment]
@digerata That project has been merged back here - thought I'd make note of that.

**Comment by akhilesharora** [comment]
Fails for user on prod after migration sometimes. If I check the Ignore2FA then it works else doesn't.
```
Processing by AccountController#login as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"5OrvYz8T87xZgpT57Kpt2MxhSL2UgRgCvxAUsrvR8T+Ym7AH1Kdu5/AB8g9f8JDMu6fBCT94kI2wLLW3oGPzEw==", "username"=>"admin", "password"=>"[FILTERED]", "login"=>"Login"}
  Current user: anonymous
Completed 500 Internal Server Error in 13ms (ActiveRecord: 8.0ms)

RQRCode::QRCodeRunTimeError (code length overflow. (1004>976). (Try a larger size!)):
  plugins/redmine_2fa/lib/redmine_2fa/patches/account_controller_patch/second_authentication_init.rb:11:in `new'
  plugins/redmine_2fa/lib/redmine_2fa/patches/account_controller_patch/second_authentication_init.rb:11:in `password_authentication'
  plugins/redmine_2fa/lib/redmine_2fa/patches/account_controller_patch/second_authentication_prepare.rb:16:in `password_authentication'
  app/controllers/account_controller.rb:205:in `authenticate_user'
  app/controllers/account_controller.rb:38:in `login'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by tahsin352** [comment]
getting same error
`RQRCodeCore::QRCodeRunTimeError: code length overflow. (740>528). (Try a larger size!)`
