### ISSUE TITLE
Change css so that qrcode still works with media="print"

### ISSUE THREAD

**Issue by snitko** [whomwah/rqrcode#21]
Current version of the css in README doesn't really work when I hit "Print" in browsers, because in Print mode most browsers ignore backgrounds. So instead of a QRCode there's just empty white space. I changed css a little, it now uses borders instead of the background and works well in print mode:

    td {
      border-left: solid 6px #000;
      padding: 0; 
      margin: 0; 
      width: 0px; 
      height: 6px; 
    }
    td.black { border-color: #000; }
    td.white { border-color: #fff; }

**Comment by bjornblomqvist** [comment]
Nice solution. I have just added it to the Readme.
