### ISSUE TITLE
Support crisp rendering so as to avoid ghosting and antialiasing

### ISSUE THREAD

**Issue by clord** [whomwah/rqrcode#29]
I am rendering SVGs produced by rqrcode into a canvas, and the browser is causing fine white lines around every box in the output. I've traced the issue and it seems the problem is antialiasing on internal rects of the qrcode.

The [shape-rendering](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/shape-rendering) attribute can be used to control antialiasing. I believe setting `crispEdges` will greatly improve the rendering of the SVG output of rqrcode, since its output consists mainly of vertical and horizontal edges.

**Comment by bjornblomqvist** [comment]
As i don't use the svg rendering myself, maybe you could try this fix yourself and send me a pull request if your changes fixes the problem you are seeing?

Or maybe just applying a CSS styling could solve your problem? See https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Getting_started/SVG_and_CSS and i *believe* what you want is 

    svg rect {
      shape-rendering: crispEdges;
    }

I have not tested this myself so it might not work as expected.

**Comment by clord** [comment]
The css trick should work for inline svg, but not when embedded with `img` tag.

I'll whip up a pull request.
