### ISSUE TITLE
UTF8 strings under Ruby 1.9.2

### ISSUE THREAD

**Issue by defeated** [whomwah/rqrcode#3]
Generating a QR Code from a UTF8 string under Ruby 1.8.7 works fine

But under Ruby 1.9.2, the same UTF8 string creates a different looking QR code. When you scan the code, the results doen't match the original input string.

**Comment by bjornblomqvist** [comment]
This has been fixed in https://github.com/whomwah/rqrcode/commit/79ac6c29aa205066dfe7b55eaa618e617463905c
