### ISSUE TITLE
Generating a "number" QR code

### ISSUE THREAD

**Issue by toncid** [whomwah/rqrcode#33]
Hello,

Is there a way to produce a number QR code? It is mentioned as the `QRMODE[:mode_number]` hash value, but I cannot find where it is used. 

Any suggestions?

**Comment by bjornblomqvist** [comment]
Sorry but that's in the TODO still.

I you feel up to it you could probably add it yourself. Checkout this [website](http://www.thonky.com/qr-code-tutorial/data-encoding) for how qrcode works and my [commit](https://github.com/whomwah/rqrcode/commit/277dc6925ab6d1d6a2a61882ca91643758e19edf) for alphanumeric on how to add it to rqrcode.

**Comment by toncid** [comment]
Submitted #34. Please review it and let me know.

I haven't added any new tests though...
