### ISSUE TITLE
Support for version 11-40 codes

### ISSUE THREAD

**Issue by fabn** [whomwah/rqrcode#35]
According to [QR standards](http://web.archive.org/web/20110710094556/http://www.denso-wave.com/qrcode/vertable4-e.html) they can store up to 2953 generic bytes (version 40, level L).

This library only supports versions 1-10. Is there any plan to support extended versions?

**Comment by bjornblomqvist** [comment]
Why do you think the library only supports levels 1-10?

I just tried to make a level 20 qrcode that worked. But it does seam like levels above 20 are broken in some way =(.

**Comment by bjornblomqvist** [comment]
I seams like it was my qrcode scanner that couldn't do above level 20. With http://www.onlinebarcodereader.com/ i have been able to scan qrcode up to level 32.

**Comment by fabn** [comment]
I was looking at this [table](https://github.com/whomwah/rqrcode/blob/master/lib/rqrcode/qrcode/qr_code.rb#L62) and at the method [smallest_size_for](https://github.com/whomwah/rqrcode/blob/master/lib/rqrcode/qrcode/qr_code.rb#L397) which automatically select size according to previous table.

```ruby
# Should use level 21 with mode_8bit_byte
RQRCode::QRCode.new('a' * 383, level: :h)
#=> RQRCode::QRCodeRunTimeError: code length overflow. (383 digits > any version capacity)

# Should use level 11 with mode_alpha_numk
RQRCode::QRCode.new('A' * 225, level: :h, mode: :mode_alpha_numk) 
# => RQRCode::QRCodeRunTimeError: code length overflow. (225 digits > any version capacity)
```

By looking better at those tables it seems that the currently supported versions are
```
mode_number => version 1-10
mode_alpha_numk => version 1-10
mode_8bit_byte => version 1-20
mode_kanji => support dropped
```

**Comment by fabn** [comment]
> i have been able to scan qrcode up to level 32.

How did you generate a lev 32 qr code?

**Comment by bjornblomqvist** [comment]
I had forgotten about that. I think that's the only think blocking it from working with a higher level. If you create a pull request with the correct values from http://web.archive.org/web/20110710094556/http://www.denso-wave.com/qrcode/vertable4-e.html then i will merge and release.

**Comment by bjornblomqvist** [comment]
RQRCode::QRCode.new( "S" * 2520, :size => 32, :level => :l ).as_png(:file => "/tmp/out3.png")

**Comment by fabn** [comment]
Yes, I just saw that by myself :+1: 

I was using automatic size, for that reason I got those errors.

I'll try to submit a PR later.

**Comment by bjornblomqvist** [comment]
I just love this.. People find problems and fix them =)
