### ISSUE TITLE
Saving as PNG and setting color at the same time doesnt work

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [whomwah/rqrcode#38]
I tried to save my image with color directly to a file - didnt work, the color is discarded:

``` ruby
image.as_png(color: 0x114163FF, file: "tmp/cache/qr_#{user.id}.png")
```

But this one does work (chaining methods):

``` ruby
image.as_png(color: 0x114163FF).save("tmp/cache/qr_#{user.id}.png")
```

The reason is in /lib/rqrcode/export/png.rb:108

``` ruby
# here is the color discarded, due to greyscale mode
if output_file
   png.save(output_file,{ :color_mode => ChunkyPNG::COLOR_GRAYSCALE, :bit_depth =>1})
end
```

Thanks for the great library!

**Comment by bjornblomqvist** [comment]
Do you think you could do a pull request with a fix ?

**Comment by lichtamberg** [comment]
Sure, shall I just remove the greyscale color mode or shall i check, if there is a color, then it's color, otherwise its greyscale?

**Comment by bjornblomqvist** [comment]
I think a check would be the nicer option. Then the result wont change for does not setting the color =)

**Comment by bjornblomqvist** [comment]
@lichtamberg do still wish do this fix?

**Comment by CostaRico** [comment]
Such code doesnt work with this PR.

png = qrcode.as_png(
				resize_gte_to: false,
				resize_exactly_to: false,
				fill: '#FAFAFA',
				color: '#f43c12',
				size: 300,
				border_modules: 4,
				module_px_size: 6,
				file: tmp_file.path # path to write
			)

**Comment by imi56** [comment]
How can I save this generated png to S3 using `paperclip`?

**Comment by metalelf0** [comment]
Hi all, I'm generating a QR code and - later - overlaying a color logo on it with mini_magick. The png returned by `as_png` is a greyscale image even if I set `color_mode: ChunkyPNG::COLOR_TRUECOLOR`, so the resulting image after I overlay my logo is greyscale. The hack I've found is to also set a foreground color, e.g. `color: #111112`, but this is counter intuitive. I think that the `color_mode` option, when set to `ChunkyPNG::COLOR_TRUECOLOR`, should always return a PNG with the colorspace set to color, even if the QR code is black. What do you think?
