### ISSUE TITLE
0.9.0 does not work on unicorn

### ISSUE THREAD

**Issue by rmargalit** [whomwah/rqrcode#39]
Yikes!
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require': No such file to load -- rqrcode (LoadError)

Had to force 0.8.0

**Comment by bjornblomqvist** [comment]
Do you think you could dig a bit deeper? I have looked at all the commits between 0.8 and 0.9 and i cant find anything that should cause problems.

**Comment by rmargalit** [comment]
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require': No such file to load -- rqrcode (LoadError)
	from /usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `block in require'
	from /usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:213:in `load_dependency'
	from /usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require'
	from /shelfx/Configuration/app/controllers/fixtures_controller.rb:4:in `<class:FixturesController>'
	from /shelfx/Configuration/app/controllers/fixtures_controller.rb:1:in `<top (required)>'

Ran Margalit
ShelfX – CEO
Tel : 1-855-4-SHELFX
Alt Tel: 720-897-7731
Mobile: 720-217-7731
Skype: ranmargalit
www.shelfx.com
Like ShelfX on Facebook <https://www.facebook.com/ShelfX?ref=tn_tnmn>Follow us on Twitter <https://twitter.com/ShelfxUSA>

**Comment by rmargalit** [comment]
Found it.
It has to do with how you start unicorn.
If I kill all processes first and run it, it does not load.
You have to wait…

Ran Margalit
ShelfX – CEO
Tel : 1-855-4-SHELFX
Alt Tel: 720-897-7731
Mobile: 720-217-7731
Skype: ranmargalit
www.shelfx.com <http://www.shelfx.com/>
Like ShelfX on Facebook <https://www.facebook.com/ShelfX?ref=tn_tnmn>Follow us on Twitter <https://twitter.com/ShelfxUSA>

**Comment by bjornblomqvist** [comment]
Your last message is a bit hard to understand.. Did you find a solution or are you still having problems?

**Comment by rmargalit** [comment]
The issue was the killing the unicorn processes and starting it immediately, it does not load properly (Prawn as well).

Ran Margalit
ShelfX – CEO
Tel : 1-855-4-SHELFX
Alt Tel: 720-897-7731
Mobile: 720-217-7731
Skype: ranmargalit
www.shelfx.com
Like ShelfX on Facebook <https://www.facebook.com/ShelfX?ref=tn_tnmn>Follow us on Twitter <https://twitter.com/ShelfxUSA>

**Comment by bjornblomqvist** [comment]
I closed this as it looks to be a Unicorn or restart script related issue.
