### ISSUE TITLE
A way to put a logo inside the QR

### ISSUE THREAD

**Issue by mareczek** [whomwah/rqrcode#42]
Thank you for a great tool!
Is there a way to put images inside the QR are?

**Comment by bjornblomqvist** [comment]
Sorry but that's not something that's supported by this library. But you could probably get away with just using ImageMagic to insert an image in the center of a qrcode.

Having images in qrcodes is a bit of a trial and error.

**Comment by pjforde1978** [comment]
@bjornblomqvist I suspect that what @mareczek (and I) are looking for is an implementation of what Denso Wave refers to as [Frame QR](https://www.denso-wave.com/en/system/qr/product/frame.html).

It seems likely that one could just put a logo in the middle of the code and rely on error correction to solve the problem. However, if there's a more elegant solution, it would be pretty amazing to see it in the library.

I would offer to submit a PR but I actually don't know how the sausage gets made and the math is likely above my pay grade.
