### ISSUE TITLE
saving an png through an error

### ISSUE THREAD

**Issue by colorfulberry** [whomwah/rqrcode#43]
```
qrcode = RQRCode::QRCode.new("http://github.com/")
# With default options specified explicitly
png = qrcode.as_png(
          resize_gte_to: false,
          resize_exactly_to: false,
          fill: 'white',
          color: 'black',
          size: 120,
          border_modules: 4,
          module_px_size: 6,
          file: nil # path to write
          )
IO.write("/tmp/github-qrcode.png", png.to_s)
```

But through error like this
`"\x89" from ASCII-8BIT to UTF-8`

**Comment by gkunwar** [comment]
@colorfulberry @gioele @bjornblomqvist @whomwah @fabn @all Is there any progress in this issue?

**Comment by shivabhusal** [comment]
Hey @colorfulberry could you please update the comment with
`OS and version`, `ruby version`, `gem version`

Because Its working fine in my system

---
```
Ruby - 2.3.1, 2.1.3
OS: Ubuntu 14.04
Gem version: 0.10.1, 
```

**Comment by gkunwar** [comment]
@shivabhusal Following is my system 
```
Ruby 2.3.1
OS: OS X Yosemite version 10.10
RQRCode Gem version: 0.10.1
```

**Comment by gkunwar** [comment]
@clord @colorfulberry Anyone is working in this issue?

**Comment by whomwah** [comment]
@gkunwar it looks like no one is actually working on this. If you want to submit a PR for this issue yourself, the instruction are on in the README.

**Comment by gkunwar** [comment]
@whomwah Sure.

**Comment by colorfulberry** [comment]
I am sorry, It works for me at last, Thanks

**Comment by pmackay** [comment]
I also found this error. For reference, writing a file by setting the `file` param of the `as_png` call _does_ work.

**Comment by courtsimas** [comment]
...or calling the `png.to_data_url` instead of `png.to_s` will actually work.
