### ISSUE TITLE
Add logo or change color of QR codes

### ISSUE THREAD

**Issue by hoahm** [whomwah/rqrcode#49]
Hi, everyone.

I want to make some customization of generating QR codes, such as inserting a logo or changing the background color. 

Do you have any idea how to do it, please show me how?

**Comment by samvandamme** [comment]
+1 would like this too...

**Comment by pchaganti** [comment]
👍

**Comment by medright** [comment]
wouldn't the background color just be set via your css for wherever you are displaying the qr? otherwise you can change the fill color, you'll just need to make sure your "fill" and "color" values have enough contrast..

```css

png = qrcode.as_png(
          resize_gte_to: false,
          resize_exactly_to: false,
          fill: 'white',
          color: 'black',
          size: 120,
          border_modules: 4,
          module_px_size: 6,
          file: nil # path to write
          )
```

what are you thinking for logo use, as a background or in a qr in the shape of a logo? the common use seems to be putting a logo in a white space in the center of the qr

**Comment by richin13** [comment]
+1 for the logo thing

**Comment by Rigel89** [comment]
+1 for this feature

**Comment by JoeWoodward** [comment]
A logo in the center of the QR would be perfect for my use case

**Comment by mareczek** [comment]
+1

**Comment by matpol88** [comment]
Where do we add this code? 

```
png = qrcode.as_png(
          resize_gte_to: false,
          resize_exactly_to: false,
          fill: 'white',
          color: 'black',
          size: 120,
          border_modules: 4,
          module_px_size: 6,
          file: nil # path to write
          )
```

**Comment by kuzevanoff** [comment]
What about logo? 
THanks

**Comment by 8parth** [comment]
I am trying to generate QR code with blue color. I am using following code:

`qrcode = RQRCode::QRCode.new('abc').as_png(fill: 'white', color: 'blue', file: 'tmp/abc.png')`

However, I only get QR code in black and white color.

**Comment by anuaimi** [comment]
While the code allows a fill color, when it saves the file to disk, it forces it to a black and white image.  That's why you don't get a QR code that matches the fill and color parameters.

```
        if output_file
          png.save(output_file,{ :color_mode => ChunkyPNG::COLOR_GRAYSCALE, :bit_depth =>1})
        end
```

To change this, you need to fork the repo and change that line

**Comment by anuaimi** [comment]
I used RMagick to add a logo onto the QR code.  Once you have saved the QR code to disk, here is some sample code to merge a logo into the centre. Note, the logo needs to have a transparent background for this to work.

```
    # now watermark with logo
    # magick composite -gravity center App_qr_icon_small.png li-source.png  final.png
    qrImage =  Image.read(qrCodeFile)[0]
    logoImage = Image.read("icon_transparent.png")[0]
    finalImage = qrImage.composite( logoImage, CenterGravity, OverCompositeOp)
    finalImage.write(qr_code_filename)
```

**Comment by pchaganti** [comment]
👍

**Comment by topherwsl** [comment]
hi, 

when i try to composite the image using "Over" as the compose attribute, the QR output will be black and white, including my logo.

```
qr_code = RQRCode::QRCode.new(url)

qr_png = qr_code.as_png(
  color: "black",
  fill: "white",
  size: 2000
)

# Open QR-Code image with MiniMagick
qrcode_image = MiniMagick::Image.create do |f|
  f.write(qr_png)
end

# Open logo with MiniMagick and resize it if needed
logo_image = MiniMagick::Image.open("QRs/#{merchant}/#{logo}")
logo_image.resize("600x600")

# Combine both images
result = qrcode_image.composite(logo_image) do |c|
  c.compose "Over"
  c.geometry "+800+800"
end

IO.binwrite("QRs/#{merchant}/qr.png", result.to_blob.to_s)
```

![image](https://user-images.githubusercontent.com/12619488/193089576-fef36de8-2f2b-4bf5-a967-61c74aabdc67.png)

**Comment by aeronpostale27** [comment]
@topherwsl 

Put colored value in color:

like color: "#14124a"

qrcode_image = MiniMagick::Image.create do |f|
        f.write(qrcode.as_png(
          color: "#14124a",
          resize_exactly_to: false,
          resize_gte_to: false,
          size: 320
        ))
      end

**Comment by topherwsl** [comment]
> @topherwsl
> 
> Put colored value in color:
> 
> like color: "#14124a" instead of black
> 
> qr_png = qr_code.as_png( color: "black", fill: "white", size: 2000 )

hi thanks for the answer.

it works but what if i want black QR with image on top?

what colour code should i apply because #000000 gives me the same result.

**Comment by aeronpostale27** [comment]
You can choose a color that's almost black like this: #0d0d19

**Comment by topherwsl** [comment]
works perfectly! tq so much @aeronpostale27
