### ISSUE TITLE
png.to_s 500 error

### ISSUE THREAD

**Issue by yumikohey** [whomwah/rqrcode#54]
I followed the example, and when I used `png.to_s`, I got 
Encoding::UndefinedConversionError ("\x89" from ASCII-8BIT to UTF-8):

However, I use `png.to_data_url`, it successfully passed to front end.

**Comment by kncxstudio** [comment]
try to add 

> # coding = utf8

**Comment by courtsimas** [comment]
I too, had the same issue. This should be in the readme somewhere.
