### ISSUE TITLE
Auto size and how to set it

### ISSUE THREAD

**Issue by MicheleNutmeg** [whomwah/rqrcode#55]
Hi guys,
I've seen that in release 0.9.0 it has `added support for auto selecting qrcode size up to 40` but I've also seen that the default size is `4`.

what value should I use for the size property to auto select the size?

if this code is setting an auto size `RQRCode::QRCode.new("http://github.com/")` then when is the default value used?

Cheers

**Comment by bjornblomqvist** [comment]
The default value is not used any longer. If you exclude the size the code will use the smallest possible qrcode size.
