### ISSUE TITLE
Embedding svg inside svg

### ISSUE THREAD

**Issue by nofxx** [whomwah/rqrcode#59]
Just an idea, but also could be a good refactor:

https://github.com/whomwah/rqrcode/blob/a93d1145a257969a1e85979bc430a8f8bf913d5a/lib/rqrcode/export/svg.rb#L26

Headers and opening closes could be in a separated method. 
One use case is embedding: There's some rule that you shall not have ```<svg>``` inside ```<svg>```.
To circunvent, I'm parsing #as_svg and using children.

**Comment by bjornblomqvist** [comment]
You are the first person who has requested it so its really not something i would do right now.

Given that the output is predictable you should be able to strip out unwanted tags using gsub.

**Comment by berkes** [comment]
I also needed this feature, so I attempted a backwards compatible version in PR #72
