### ISSUE TITLE
Rectangular QR Code

### ISSUE THREAD

**Issue by bcackerman** [whomwah/rqrcode#63]
Is there a way of doing this? 
![image](https://user-images.githubusercontent.com/473529/39586135-ff598000-4ebb-11e8-81f9-5698df79111f.png)

**Comment by bjornblomqvist** [comment]
No.. QR codes follow a strict standard. They can never be rectangular.

**Comment by Syndesi** [comment]
Rectangular QR codes are possible, see https://www.qrcode.com/en/codes/rmqr.html for the specs and https://github.com/OUDON/rmqrcode-python for a reference implementation.

Though while they are standardized, only a very few code scanning apps do support them, e.g. Scandit Demo and QRQR Code.

**Comment by Diman2003** [comment]
How scan it please add scanning section of code in this lib
