### ISSUE TITLE
Getting NoMethodError when using RQRCode

### ISSUE THREAD

**Issue by alliedarmour** [whomwah/rqrcode#75]
When I'm trying to render the QR-Code with the example given, I get the following error and I can't figure out why:

undefined method `is_dark?' for #<RQRCode::QRCode:0x000000000707ec78>

If I call the method in console it doesn't find it aswell :/.

**Comment by whomwah** [comment]
which version are you using? and which example?` `is_dark?` is not a method. You can now use `instance.qrcode.checked?( row, col )`. Also if you do not need a specific rendering and want to look though the qrcode manually, maybe you just need `rqrcode_core`.
