### ISSUE TITLE
Introduce new render method as CSS

### ISSUE THREAD

**Issue by krtschmr** [whomwah/rqrcode#77]
i've implemented for our project a render method css. i did this via rails_helper

the styling is done 100% via CSS so it's fully customizable, for example having rounded data instead of just squares. different coloring, also possible. the logo is just a png that will be positioned centered. up or down scaling is done by px calculation

i can share the helper module, but i wonder, what would be the best way to integrate it into this gem? i can imagine it's useful for people who want customization.  for example, look at the anchors (those squares). some of the corners are rounded (each has individual classes, so you can style them one for one)

feel free to try it out and please let me know how we could implement this as a render method

helper is: https://gist.github.com/krtschmr/9e7b297763901efbe6cf02b4cb13ae5f

i can call it like this

```
.row.mb-5=qr_code(instruction.to_qr, logo_size: 24)
.row.mb-5=qr_code(instruction.to_qr, level: :h)
.row.mb-5=qr_code(instruction.to_qr, width: 350, logo_size: 64, level: :h)
```
and it renders me

![image](https://user-images.githubusercontent.com/13366714/66110145-b92baf80-e5b5-11e9-9acc-e3925ae596ad.png)

**Comment by whomwah** [comment]
Thanks for the above, but I'm not adding any more render types to the project. My suggestion would be to create your own `rqrcode_to_css` gem using the underlying https://github.com/whomwah/rqrcode_core lib.
