### ISSUE TITLE
Lacking a CHANGELOG.md file

### ISSUE THREAD

**Issue by dbackeus** [whomwah/rqrcode#82]
Would be helpful if the gem included a `CHANGELOG.md` to make it straight forward to figure out what to look out for when updating.

These tend to be automatically parsed by dependency tools such as [dependabot](https://dependabot.com/) as well which makes for great developer experience.

Example of formatting: https://github.com/stripe/stripe-ruby/blob/master/CHANGELOG.md

**Comment by thomasbalsloev** [comment]
@dbackeus  I second that.

**Comment by whomwah** [comment]
I realise there's been a long delay in relying here. I've add this to a TODO list. The gem does not get many releases these days  but I understand how it would be useful. PRs are welcome in the mean time.
