### ISSUE TITLE
Not able to create image

### ISSUE THREAD

**Issue by carlosMedrano27** [whomwah/rqrcode#83]
Getting the following error `Encoding::UndefinedConversionError ("\x89" from ASCII-8BIT to UTF-8)` on saving png image as the README shows

**Comment by cis-ankitk** [comment]
Did you found solution for this?
I am facing same issue

**Comment by cnhuye** [comment]
I found the answer from google.

`png.save(filename, :interlace => true)`

ref:  https://github.com/wvanbergen/chunky_png

**Comment by cis-ankitk** [comment]
Yes I have also found this and its working fine
Thank you :+1:
