### ISSUE TITLE
Edit @data of RQRCode::QRCode instance

### ISSUE THREAD

**Issue by Hemanshu-Thakker** [whomwah/rqrcode#90]
<h5>My requirement</h5>
<p>I need to generate dynamic qr codes such that the qr code remains the same but the content i.e the url it is mapped to changes frequently</p>
<p>The code to generate a new QR code is @qr = RQRCode::QRCode.new('url_string')</p>
<p>Here @qr is an instance of RQRCode::QRCode which returns
<br> QRCodeCore: @data='url_string', @error_correct_level=2, @version=4, @module_count=33 </p>
<p>I am able to access @version and other variables except @data using @qr.qrcode.version</p>
<br>
<p><b>How to edit the url_string/@data for a qrcode</b></p>

**Comment by whomwah** [comment]
You cannot edit the `string` as that is the basis of the QR Code that is rendered. If you change the `string` then you will get a different QR Code rendering.
