### ISSUE TITLE
Ability to add image to centre of QR code

### ISSUE THREAD

**Issue by barnaclebarnes** [whomwah/rqrcode#91]
It would be nice to be able to add a custom image to the middle of the QR code (something like the image below). 

![qr-code](https://user-images.githubusercontent.com/10322/90585387-d9de1180-e228-11ea-92eb-27ccc0a67e5c.png)

**Comment by SebastianPoell** [comment]
My solution for now simply uses MiniMagick:
 
```ruby
require "mini_magick"

# Create QR-Code image
qrcode = RQRCode::QRCode.new("SOME_URL...")

# Open QR-Code image with MiniMagick
qrcode_image = MiniMagick::Image.create do |f|
  f.write(qrcode.as_png(
    size: 2000
  ))
end

# Open logo with MiniMagick and resize it if needed
logo_image = MiniMagick::Image.open("LOGO_URL...")
logo_image.resize("400x400")

# Combine both images
result = qrcode_image.composite(logo_image) do |c|
  c.compose "Over"
  c.geometry "+800+800"
end
    
# Return combined image data
result.to_blob
```

In case you want to save it to ActiveStorage in Rails:
```ruby
qr_code_image.attach(
  filename: "qr_code",
  io: StringIO.new(result.to_blob),
  content_type: "image/png"
)
```

HTH

**Comment by gdonnelly82** [comment]
@barnaclebarnes @sebastianPoell 

How do you create the white Square in the middle of the QR Code so that when you add the logo with MiniMagick it wont break the QR code?

Thanks

**Comment by SebastianPoell** [comment]
Hi, not sure if I understand your question correctly, but you can always occlude parts of the QR-Code without breaking it. This is part of the QR-Codes error correction. So, if you simply put a logo (e.g. with white background) in the middle of the QR-Code, it will still work (as long as the logo is not too big).

**Comment by whomwah** [comment]
Like @SebastianPoell says, you can abuse the QR Code error correction to do this currently using something like `mini_magick` so it's not the sort of functionality that will be added to this gem.
