### ISSUE TITLE
Logo inclusion

### ISSUE THREAD

**Issue by gdonnelly82** [whomwah/rqrcode#94]
Great gem. 

I was wondering if there is a way to add a logo to the qrcode? 

If not, is there the ability to leave an area in the center of the QR code white and then we could use image magic to overlay a logo in the center.

See this Snapchat examples below. 
https://www.google.com/url?sa=i&url=https%3A%2F%2Fmedium.com%2F%40isabeljl%2Fsnapcodes-uncomplicated-qr-coding-d9b431206c05&psig=AOvVaw2pzdMwk1a8YdH4PiqT8fw8&ust=1607380373539000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCODLodO0uu0CFQAAAAAdAAAAABAN

Thanks for any advice in advance. 
![snapqrcode](https://user-images.githubusercontent.com/59867883/101295113-7c8bc180-3813-11eb-87b4-1e4416ecc981.png)

**Comment by barnaclebarnes** [comment]
I think specifying a blank area in the middle would be the best approach. Then you can post process this in whatever way you want.  Maybe setting a "cutout_percentage` and possible a `cutout_shape`?

**Comment by barnaclebarnes** [comment]
Also dup of #91 ;-)
