### ISSUE TITLE
Ruby 3.0 support 

### ISSUE THREAD

**Issue by AndreaRibuoli** [whomwah/rqrcode#95]
Is *rqrcode* planned to support Ruby 3.0? Thanks.

**Comment by clwy-cn** [comment]
rqrcode_core-0.1.2 requires ruby version ~> 2.3, which is incompatible with the current version, ruby 3.0.0p0

**Comment by whomwah** [comment]
A new version of both was released yesterday.

**Comment by AndreaRibuoli** [comment]
Thank you! Working for me with:

```
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [powerpc-os400]
```
